### ISSUE TITLE
Colab notebooks currently broken from upstream dependency 

### ISSUE THREAD

**Issue by sef43** [openmm/openmm-cookbook#36]
The Colab notebooks are broken untilll this issue in condacolab is fixed: https://github.com/conda-incubator/condacolab/issues/60

Error you get when running in colab is:
```
No package can be installed for pin: cudatoolkit 12.2.*

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/lib/python3.10/site-packages/mamba/mamba.py", line 547, in install
        solver.add_pin(final_spec)
    RuntimeError: No package can be installed for pin: cudatoolkit 12.2.*

`$ /usr/local/bin/mamba install openmm`
```

**Comment by epretti** [comment]
In #42 we switched from condacolab to pip for installing OpenMM, so the notebooks are working again.  We will have to revisit this if we make a notebook requiring a package available only on conda-forge and not on PyPI, but for now, this is not the case.
